services:
  - type: web
    name: dans-dan
    env: node
    plan: free
    region: frankfurt

    buildCommand: yarn install --force
    startCommand: yarn start

    autoDeploy: true
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        value: "2547xxxxxxxx"
      - key: BOT_NAME
        value: "DansDan"
      - key: DATABASE_URL
        sync: false